database:
    image: mysql:5.7
    ports:
        - "3306:3306"
    command: --init-file /data/init.sql
    volumes:
        - ./init.sql:/data/init.sql
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: 
        MYSQL_DATABASE: dev